# Generated by Django 4.1.1 on 2022-09-14 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroomuser',
            old_name='chat_room_id',
            new_name='chat_room',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chat_room_id',
            new_name='chat_room',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creator_user_id',
            new_name='creator_user',
        ),
    ]
