# Generated by Django 4.1.1 on 2022-09-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.TextField(default='abcd,efgh'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatroom',
            name='state',
            field=models.CharField(default='PENDING', max_length=200),
            preserve_default=False,
        ),
    ]
