# Generated by Django 4.1.1 on 2022-09-14 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_chat_room_id_chatroomuser_chat_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='creator_user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='chatroomuser',
            name='invited_time',
            field=models.DateTimeField(),
        ),
    ]
