# Generated by Django 4.1.1 on 2022-09-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_name_chatroom_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='state',
        ),
        migrations.AddField(
            model_name='chatroomuser',
            name='state',
            field=models.CharField(default='INVITED', max_length=200),
            preserve_default=False,
        ),
    ]
