# Generated by Django 4.1.1 on 2022-09-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_creator_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
