# Generated by Django 4.1.1 on 2022-09-16 15:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_usermessagemetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessagemetadata',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
