# Generated by Django 4.1.1 on 2022-09-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroomuser',
            name='invited_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='chatroomuser',
            name='joined_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
