# Generated by Django 4.1.1 on 2022-09-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatroomuser_invited_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroomuser',
            name='invited_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='chatroomuser',
            name='joined_time',
            field=models.DateTimeField(null=True),
        ),
    ]
