# Generated by Django 4.1.1 on 2022-09-14 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chatroomuser_invited_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
