# Generated by Django 4.1.1 on 2022-10-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatroomuser_last_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='last_updated_time',
            field=models.DateTimeField(null=True),
        ),
    ]
